### ISSUE TITLE
SpatialBatchNormalization Issue

### ISSUE THREAD

**Issue by apage2** [soumith/cudnn.torch#115]
I recently updated (Feb. 17) to the latest versions, i.e. cuDNN v4 (Feb. 10), nn, cutorch, cunn, and cudnn.torch. The problem I am seeing is that my networks are no longer able to learn... I rechecked my code, installation, and everything seems okay. I systematically started swapping out cudnn backend with nn equivalent and it seems that SpatialBatchNormalization is not working as expected. On CIFAR-10, I can get 93% when I use everything with cudnn backend but with nn.SpatialBatchNormalization. When I use cudnn.SpatialBatchNormalization I can't get past 10% (always guessing same label).

Any thoughts? I can investigate more but looking at the commit logs I see a number of substantial changes to SpatialBatchNormalization.

Thanks.

**Comment by soumith** [comment]
@apage2 that sounds strange, happy to investigate. have you tried this code: https://github.com/szagoruyko/cifar.torch and see the same behavior?

**Comment by szagoruyko** [comment]
I know what's the issue, I forgot to add reset function, preparing a PR

**Comment by fmassa** [comment]
There is already a PR for that https://github.com/soumith/cudnn.torch/pull/114

**Comment by szagoruyko** [comment]
@fmassa it wont work, no check for weight, bias and no running mean and std reset.

**Comment by fmassa** [comment]
There is no option to remove the weight and bias from `cudnn.SpatialBatchNormalization`, plus the running mean and std are already set to zeros and ones.

**Comment by soumith** [comment]
ugh guys we cant have this kind of regressions. can you add tests for a case where we catch this issue?

**Comment by szagoruyko** [comment]
@fmassa ah right. reset function is not just for ctor, can be called elsewhere.

**Comment by soumith** [comment]
so should I merge #116?

**Comment by fmassa** [comment]
I think #116 is fine.
BTW, this regression was introduced in the original BatchNorm 4.0 PR https://github.com/soumith/cudnn.torch/pull/101

**Comment by soumith** [comment]
ok there's #116 and there's #114 
Sergey, merge whichever is correct, i'll update distro in 30 mins

**Comment by szagoruyko** [comment]
@soumith let me add a test. we should it to nn too btw.

**Comment by soumith** [comment]
@apage2 updating your cudnn.torch package via the command: (luarocks install cudnn) should fix things. sorry about that.

**Comment by apage2** [comment]
Nice, that was fast. I reran and it is working as expected.

Thanks.
