### ISSUE TITLE
cudnn.convert() isn't converting ReLU() modules back to nn

### ISSUE THREAD

**Issue by willfrey** [soumith/cudnn.torch#122]
I have a GPU model `gpu_net` that I'd like to convert back to be a CPU model. I'm doing this with two calls `cpu_net = gpu_net:clone():float()` followed by `cudnn.convert(cpu_net, nn)`.

Unfortunately, this doesn't seem to be working. If I look at the output of `cpu_net:listModules()`, I still see instances of ReLU modules having `self.mode = CUDNN_ACTIVATION_RELU`.

If I save my CPU model to an ascii file and search through it for instances of 'cudnn', I find thousands.

I tried manually setting the `self.mode` instances to nil, but it didn't work.

For what it's worth, I'm using Element Research's `rnn` package extensively. Perhaps `cudnn.convert()` isn't cooperating with that?

Thanks.

**Comment by szagoruyko** [comment]
`self.mode` in ReLU should not be a problem, it is not used in nn and does not depend on cudnn. If you have cudnn modules inside rnn's that's probably the issue, clearState is not propagating into rnn modules.

**Comment by willfrey** [comment]
Thanks for the response!

Do you have any suggestions for manually fixing this? I'm digging around myself but I'd still consider myself a Torch novice.

**Comment by willfrey** [comment]
Closing this as it probably doesn't matter much with the release of R5 and the native cudnn RNN modules.
