### ISSUE TITLE
Convert and clearState

### ISSUE THREAD

**Issue by melgor** [soumith/cudnn.torch#138]
Recently I want to use "convert" method to reduce the size of models(https://github.com/cmusatyalab/openface/pull/110) . And my previous method worked much better than clearState. I found why:
1. "_gradOutput" is never cleared in any module.
2. "gradBias" and "gradWeight" are not cleared in SpatialConvolution
Shouldn't this buffers be added to "clearState" function?

The last thing is this [line](https://github.com/soumith/cudnn.torch/blob/R4/convert.lua#L44). Why not using "clearState()" here, no matter if this is 'nn' or 'cudnn' version? 
I think that "clearState()" can have different implementation in nn and cudnn what can cause buffers which have occured in cudnn version will not be cleared.

**Comment by fmassa** [comment]
Indeed, `_gradOutput` and `_input` are not cleared in `clearState`, as [mentioned in here](https://github.com/soumith/cudnn.torch/commit/af7240b9ce4058b7490014987803b077e9191566#commitcomment-16346092) and that should be included.
About `gradWeight` and `gradBias`, as mentioned in https://github.com/cmusatyalab/openface/pull/110, we can't only free them, but we also need to reconstruct them before training, so they go out of the scope of `clearState` I think.

About calling `:clearState` instead of `:clearDesc`, I think that's a good idea. It's probably like this because `convert` was merged in before `clearState`.

**Comment by soumith** [comment]
(1) is fixed.
(2) is out of scope of clearState unfortunately.

**Comment by melgor** [comment]
@soumith  Thanks for fast response and action. I see you added _gradOutput only to SpatialConvolution, It would be great that if you can add it to [Pointwise](https://github.com/soumith/cudnn.torch/blob/master/Pointwise.lua#L40) and other [modules](https://github.com/soumith/cudnn.torch/search?utf8=%E2%9C%93&q=_gradOutput) which have "_gradOutput" buffer.

**Comment by soumith** [comment]
sure, adding it now.

**Comment by vgatto** [comment]
@soumith I understand (2) is out of scope for changes to clearState. Is there a work-around?  Even when zeroed out, gradWeight is still pretty big when written to disk.

**Comment by soumith** [comment]
@vgatto you could write a small save and load function. Save goes through the model and nils all the gradWeight and gradBias. Load goes through the model and makes gradWeight same size as weight, and gradBias same size as bias. However, sharing will break in this scheme.

**Comment by fmassa** [comment]
@vgatto to complement @soumith answer, [here is a code](https://github.com/fmassa/optimize-net/blob/master/init.lua#L302-L356) (which is present in [`optnet`](https://github.com/fmassa/optimize-net)) which does exactly what Soumith mentioned, but which also takes care of the sharing scheme.

**Comment by vgatto** [comment]
@soumith, @fmassa - Thanks for the pointers, that definitely works for me.  It seems like the long term solution would be enhancing the nn.Module interface to support this save/load case and having each module implement whatever makes sense. Basically, another clearState specifically for this purpose. Is there an enhancement issue filed for this?
