### ISSUE TITLE
print(nil) when libcudnn is not installed

### ISSUE THREAD

**Issue by nagadomi** [soumith/cudnn.torch#145]
Is this line needed?
https://github.com/soumith/cudnn.torch/blob/3f7c066fae27e202925a9f7c74eaec70130e6e2f/ffi.lua#L1278

code:
```
pcall(require, 'cudnn')
```
result:
```
nil
```
What I expected: do-nothing (or print error message if needed)

**Comment by soumith** [comment]
that line looks like a side-effect from history that should have been removed
