### ISSUE TITLE
forward call allocates gradInput?

### ISSUE THREAD

**Issue by jonathantompson** [soumith/cudnn.torch#156]
I don't really have bandwidth to address it any time soon...  But I did notice that inference only models will use 2x memory because we're allocating gradInput CudaTensors during forward calls.  We should probably defer the alloc.

**Comment by szagoruyko** [comment]
good catch, this saves a ton of memory on forward pass. I sent a PR https://github.com/soumith/cudnn.torch/pull/157

**Comment by jonathantompson** [comment]
Thanks mate!

**Comment by szagoruyko** [comment]
fixed all modules in https://github.com/soumith/cudnn.torch/pull/171
