### ISSUE TITLE
save kH in TemporalConvolution

### ISSUE THREAD

**Issue by magnux** [soumith/cudnn.torch#180]
To compute the size of the padding, if its necessary to do it manually (as is my case), we need to know the size of the kernel. In the original nn implementation the kW is preserved, but because in this case the width and height are swapping, the kH is being used in the init but not saved. So it would be nice to include the following line in the init:
`local kH = kH`
This would save me the ugly workaround to calculate the padding.

**Comment by ngimel** [comment]
It is saved as self.kH:

```
th> conv = cudnn.TemporalConvolution(128,128,5)
th> conv.kW
128	
th> conv.kH
5	
```

**Comment by magnux** [comment]
You're right, I had a bug in my code apparently. Sorry :).
