### ISSUE TITLE
[R5]LSTM bias parameters

### ISSUE THREAD

**Issue by JoostvDoorn** [soumith/cudnn.torch#181]
Are the GRU and LSTM modules supposed to have 6 bias parameters? If so, are all these parameters used? I am looking into conversion to cudnn LSTM, but the number of parameters doesn't match.

**Comment by ngimel** [comment]
GRU is supposed to have 6 bias parameters, LSTM is supposed to have 8. PLease refer to cudnn manual for information on what operations are performed in each mode (in particular, section on cudnnRNNMode_t in cuDNN datatypes reference.

**Comment by JoostvDoorn** [comment]
I am sorry, I was looking for documentation on Google, but I forgot about the members only section. I will then just leave these bias params zero or average the bias to both of them, as I will not have 6 bias params for GRU or 8 for LSTM.
