### ISSUE TITLE
For R5 branch  Error in CuDNN: CUDNN_STATUS_NOT_INITIALIZED

### ISSUE THREAD

**Issue by shuzi** [soumith/cudnn.torch#186]
![image](https://cloud.githubusercontent.com/assets/6613848/15416382/b13c9edc-1e18-11e6-82b3-7357cb85b6ed.png)

Hi the main branch is fine for me. But when I start to use the R5 branch I get the above error
Cuda is 7.0

**Comment by ngimel** [comment]
You need cuda 7.5 and corresponding driver for cudnn V5

**Comment by shuzi** [comment]
Thanks ,  yes it works on CUDA 7.5
