### ISSUE TITLE
zero padding of cudnn.BLSTM

### ISSUE THREAD

**Issue by shuzi** [soumith/cudnn.torch#187]
Hi

for the R5 branch how should I do zero padding for cudnn.BLSTM ?
if I make the zero padding like below for a batch (size=2)
0 0  0   x1 x2 x3 0 0 0
0 0  y1  y2  y3 y4 0  0

will the cudnn.BLSTM do correctly? I mean for example  the fwd_lstm  would forward from x1 to x3 and backward from x3 to x1  and   bwd_lstm would forward from y4 to y1  and backward from y1 to y4.

**Comment by ngimel** [comment]
Please refer to the manual for information on how bidirectional networks operate. "Each layer of the the network iterates recurrently from the first input to the last and separately from the last input to the first. The outputs of the two are concatenated at each iteration giving the output of the layer."
Both forward and backward networks share the same input.

**Comment by shuzi** [comment]
ok so special treatment for zeros , thanks!
