### ISSUE TITLE
CUDA 6.5 

### ISSUE THREAD

**Issue by arashno** [soumith/cudnn.torch#195]
Hi all
I have CUDA 6.5 installed on my machine.
But when I am trying to install cudnn.torch R2, it gives me this error:

`luarocks install https://raw.githubusercontent.com/soumith/cudnn.torch/R2/cudnn-scm-1.rockspec
Using https://raw.githubusercontent.com/soumith/cudnn.torch/R2/cudnn-scm-1.rockspec... switching to 'build' mode
Initialized empty Git repository in /tmp/luarocks_cudnn-scm-1-8100/cudnn.torch/.git/
remote: Counting objects: 142, done.
remote: Compressing objects: 100% (113/113), done.
remote: Total 142 (delta 90), reused 66 (delta 27), pack-reused 0
Receiving objects: 100% (142/142), 82.00 KiB, done.
Resolving deltas: 100% (90/90), done.
cmake -E make_directory build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="/project/EvolvingAI/mnorouzz/torch/install/bin/.." -DCMAKE_INSTALL_PREFIX="/project/EvolvingAI/mnorouzz/torch/install/lib/luarocks/rocks/cudnn/scm-1" && make

-- The C compiler identification is GNU 4.4.7
-- The CXX compiler identification is GNU 4.4.7
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found Torch7 in /project/EvolvingAI/mnorouzz/torch/install
CMake Error at /apps/cmake/cmake-3.0.1/share/cmake-3.0/Modules/FindPackageHandleStandardArgs.cmake:136 (message):
  Could NOT find CUDA: Found unsuitable version "6.5", but required is at
  least "7.5" (found /apps/CUDA/cuda-6.5)
Call Stack (most recent call first):
  /apps/cmake/cmake-3.0.1/share/cmake-3.0/Modules/FindPackageHandleStandardArgs.cmake:341 (_FPHSA_FAILURE_MESSAGE)
  /apps/cmake/cmake-3.0.1/share/cmake-3.0/Modules/FindCUDA.cmake:845 (find_package_handle_standard_args)
  CMakeLists.txt:9 (FIND_PACKAGE)

-- Configuring incomplete, errors occurred!
See also "/tmp/luarocks_cudnn-scm-1-8100/cudnn.torch/build/CMakeFiles/CMakeOutput.log".

Error: Build error: Failed building.
`

I have read that just choosing R2 would be sufficient but it does not work for me.
What should I do?
Thanks

**Comment by soumith** [comment]
Locally clone the r2 branch and in the directory, run

luarocks make
