### ISSUE TITLE
R4 is Incompatible with cuda 7.0 on Jetson TX1

### ISSUE THREAD

**Issue by Tay2510** [soumith/cudnn.torch#196]
**core:** Jetson TX1
**OS:** Ubuntu 14.04 LTS 32-bit
**CUDA version:** 4.0.7 (4007)
**cudnn library (v4):** cudnn-7.0-linux-armv7-v4.0-prod.tgz

When I called try to build  `cudnn-scm-1.rockspec` in R4 I got this error:
```
-- Found Torch7 in /home/ubuntu/torch/install
CMake Error at /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
  Could NOT find CUDA: Found unsuitable version "7.0", but required is at
  least "7.5" (found /usr/local/cuda-7.0)
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:313 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-2.8/Modules/FindCUDA.cmake:806 (find_package_handle_standard_args)
  CMakeLists.txt:9 (FIND_PACKAGE)
```
The Jetson TX1 is currently [restricted in CUDA 7.0](https://devtalk.nvidia.com/default/topic/904664/jetson-tx1/cuda-7-5-for-tx1/), I thought I could still install it because the `.md` file says the minimum CUDA version required is 7.0

**Comment by soumith** [comment]
Should be fixed now, try: 

luarocks install https://raw.githubusercontent.com/soumith/cudnn.torch/R4/cudnn-scm-1.rockspec

**Comment by Tay2510** [comment]
Thank you Soumith! Specify `R4` tag in `.rockspec` file solved the problem!
