### ISSUE TITLE
Non-RNN layer after LSTM with variable sequence length

### ISSUE THREAD

**Issue by devrandom2** [soumith/cudnn.torch#204]
@soumith What's the best way to have a Linear (or some other non-RNN layer) following a LSTM layer at every timestep?

Example: I have a `cudnn.LSTM` layer has an output of shape `32 x 300 x 20` and I want to add a `nn.Linear(20, 10)` layer following that. I want that linear layer to process each of the 300 timesteps for each batch.

I tried using `nn.View` and `nn.Reshape` to change `32 x 300 x 20` to `9600 x 20` before feeding into the Linear layer, but I got errors about sequence length and contiguous tensors during backprop. Once I solved them, the network did not appear to learn during training. Is there a more simple way to do this?

In Keras, you'd use [TimeDistributed](http://keras.io/layers/wrappers/#timedistributed)

Thanks!

**Comment by soumith** [comment]
yea, there's a decorator similar to TimeDistributed in the rnn package https://github.com/Element-Research/rnn cc: @nicholas-leonard

**Comment by nicholas-leonard** [comment]
@devrandom2 Yup. It is called [Sequencer](https://github.com/Element-Research/rnn#rnn.Sequencer)

**Comment by devrandom2** [comment]
Thanks for the help! I'm rebuilding an architecture using Torch because LSTMs with TensorFlow and Theano are quite slow. Especially ones with long sequence lengths. It also looks like neither of them are going to have cuDNN RNNs in the next few weeks 

Would an architecture like this work?

It seems to be learning, but I want to make sure that I'm not missing anything major

```lua
 -- Model input is a 2D tensor with size (batchSize * seqLength) x inputDim
model = nn.Sequential()
model:add(nn.View(-1, seqLength, inputDim)) -- converts to 3D tensor with size batchSize x seqLength x inputDim
model:add(nn.Contiguous())
model:add(cudnn.LSTM(inputDim, 20, 1, true)) -- returns batchSize x seqLength x 20
model:add(nn.Contiguous())
model:add(nn.View(-1, 20)) -- reshapes so linear can handle it. 2D tensor with size (batchSize * seqLength) x 20
model:add(nn.Linear(20, 10))
model:add(cudnn.SoftMax())
 -- Model output is a 2D tensor with size (batchSize * seqLength) x 10
```

It also appears that some of these layers don't like it when I change batch sizes during training and validation. Would it just be easier to just switch to using the rnn package?

I can still use cuDNN layers with rnn, right?

Thanks again!

**Comment by nicholas-leonard** [comment]
You should be able to use rnn and cudnn together. rnn prefers `seqlen x batchsize` instead of `batchsize x seqlen` (it is more efficient):

```lua
 -- Model input is a 2D tensor with size (batchSize * seqLength) x inputDim
input = input:view(batchsize, seqlen, inputsize):transpose(1,2)

model = nn.Sequential()
model:add(nn.Contiguous())
model:add(cudnn.LSTM(inputDim, 20, 1)) -- returns seqlen x batchsize x 20
model:add(nn.Contiguous())
model:add(nn.Sequencer(nn.Linear(20,10)))
model:add(nn.Sequencer(nn.SoftMax()))
 -- Model output is a 2D tensor with size seqlen x batchsize x 10
```

**Comment by nhynes** [comment]
If you simply want a linear layer, it might be worth looking into using a [nn.TemporalConvolution](https://github.com/torch/nn/blob/master/doc/convolution.md#nn.TemporalConvolution) with unit kernel width. It seems to be slightly more memory efficient.
