### ISSUE TITLE
cudnn init failure near FFI half / FP16 types

### ISSUE THREAD

**Issue by dusty-nv** [soumith/cudnn.torch#236]
An error is thrown after requiring cudnn:   `torch/share/lua/5.1/cudnn/init.lua:40: declaration specifier expected near 'half'`

This is the line of code from init.lua:  `['torch.CudaHalfTensor']   = ffi.sizeof('half'),``

After workaround change it completes init, not sure about other impacts:    `['torch.CudaHalfTensor']   = 2,`

**Comment by soumith** [comment]
thanks for the bug report. looks like cutorch didn't load itself with half. I'll fix this case.

**Comment by dusty-nv** [comment]
OK thanks, yes currently `cutorch.hasHalf == false` when it should be true ([446](https://github.com/torch/cutorch/issues/446))

**Comment by soumith** [comment]
about the cutorch issue, replied there on the original thread.
Fixed this issue via https://github.com/soumith/cudnn.torch/commit/59ac9afc330e3b848fb204afeb8d6f2835902540
