### ISSUE TITLE
LSTM Incompatibility with torch-rnn

### ISSUE THREAD

**Issue by dgcrouse** [soumith/cudnn.torch#238]
I am working on a cuDNN fork of torch-rnn to pick up the speed and memory improvements/flexibility. A simple initial look indicates that the LSTM module should be mostly a drop-in replacement for the one in torch-rnn. Replacing the line `nn.lstm(num_input,num_hidden)` with `cudnn.lstm(num_input,num_hidden,1,false,0,true)` yields a network that runs but outputs gibberish. 

Looking at the architecture, the torch-rnn language model is batch x time dimension ordering, but running with batch-first set to true results in an error. Am I missing something about the parameter? I am still a newcomer to Torch and deep learning in general, so it is likely that I missed something there.

**Comment by soumith** [comment]
this fork has cudnn support: https://github.com/ngimel/torch-rnn#cudnn-support-optional

**Comment by dgcrouse** [comment]
Thanks for letting me know!
