### ISSUE TITLE
call model:getParameters() after model:cuda() will introduce CUDA illegal memory access error

### ISSUE THREAD

**Issue by blackyang** [soumith/cudnn.torch#243]
Everything (torch, cutorch, nn, cunn, cudnn (R4), nngraph) is up-to-date.

I have a model which is essentially a gModule with several normal layers (convolution, pooling, etc. Nothing fancy) However, when I try:

```
local model = dofile('model.lua')
model:cuda()
parameters, gradParameters = model:getParameters()

local ipt = torch.Tensor(1, 3, 240, 120):cuda()
local opt = model:forward(ipt)
```

There would be an illegal memory access error.

Calling getParameters() twice will not give any errors and my model works well:

```
local model = dofile('model.lua')
parameters, gradParameters = model:getParameters()
model:cuda()
parameters, gradParameters = model:getParameters()

local ipt = torch.Tensor(1, 3, 240, 120):cuda()
local opt = model:forward(ipt)
```

I updated several package today, previously there was no error. Could you explain to me what happens? Thanks:)

BTW Error message:
```
THCudaCheck FAIL file=/root/torch_lib/cutorch/lib/THC/generic/THCStorage.cu line=48 error=77 : an illegal memory access was enco
untered
/root/torch/install/share/lua/5.1/nn/Container.lua:67:
In 4 module of nn.Sequential:
...torch/install/share/lua/5.1/cudnn/SpatialConvolution.lua:319: cuda runtime error (77) : an illegal memory access was encounte
red at /root/torch_lib/cutorch/lib/THC/generic/THCStorage.cu:48
stack traceback:
        [C]: in function 'resize'
        ...torch/install/share/lua/5.1/cudnn/SpatialConvolution.lua:319: in function 'createIODescriptors'
        ...torch/install/share/lua/5.1/cudnn/SpatialConvolution.lua:360: in function <...torch/install/share/lua/5.1/cudnn/Spati
alConvolution.lua:357>
        [C]: in function 'xpcall'
        /root/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
        /root/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'func'
        /root/torch/install/share/lua/5.1/nngraph/gmodule.lua:345: in function 'neteval'
        /root/torch/install/share/lua/5.1/nngraph/gmodule.lua:380: in function 'forward'
```

**Comment by soumith** [comment]
@blackyang unfortunately, without a small example that I can run it is hard to debug what is happening.

You could run the network with one flag:
CUDA_LAUNCH_BLOCKING=1 th [yourscript.lua]
and see if there is a better stack trace.

If you give a small example that reproduces this issue, i can have a look.

Also, please use cudnn R5 and not cudnn R4.

**Comment by blackyang** [comment]
Thanks @soumith , I will make a small example later today.

By the way I just found that it was not a cudnn issue, since I still have such error after changing all cudnn layers to nn layers

**Comment by blackyang** [comment]
still cuda illegal access, but cannot constantly reproduce it
