### ISSUE TITLE
cudnn.SoftMax fails?

### ISSUE THREAD

**Issue by MichaelMathieu** [soumith/cudnn.torch#25]
Hi,

When I use cudnn.SoftMax, I get an assertion failed on line 21 of cudnn.SpatialSoftMax. My input is batchSize x nClasses, so it doesn't have 4 dimensions, which makes the assertion fail.

Shouldn't SoftMax handle input of dimension 2 ? Otherwise, I don't see the difference between SoftMax and SpatialSoftMax (or there is something I missed).

Michael

**Comment by soumith** [comment]
you're correct, this is a bug. will fix now.

**Comment by soumith** [comment]
actually, this is documented in README, 
-- All inputs have to be 3D or 4D(batch-mode), except ReLU, Tanh and Sigmoid

cudnn.SoftMax will ignore the spatiality and take softmax over all points in each sample

cudnn.SpatialSoftMax will take softmax for each point across feature maps.

I am fixing cudnn.SoftMax to allow 1D and 2D inputs as well.
