### ISSUE TITLE
Different result for SpatialConvolution with cudnn and nn

### ISSUE THREAD

**Issue by DmitryUlyanov** [soumith/cudnn.torch#251]
Hello, I cannot figure out why the model works differently with `cudnn` and `nn`. Please try to reproduce it. 

The code: https://gist.github.com/DmitryUlyanov/82938d41f49cf4c0580032b8c7bee43d
Model: https://transfer.sh/bq1Jn/model-10.t7

Run with: 
```
th test.lua -model_t7 model_10.t7 -input_image <path/to/image.jpg>
```

It will print out diffs between cudnn and nn outputs at every layer. For me it looks like this:
```
1	0	
nn.TVLoss
2	0	
nn.SpatialReplicationPadding(l=4, r=4, t=4, b=4)
3	0	
cudnn.SpatialConvolution(3 -> 32, 9x9)
4	0.0013251072959974	
cudnn.SpatialBatchNormalization
5	0.0013251072959974	
cudnn.ReLU
6	6664.0146484375	
cudnn.SpatialConvolution(32 -> 64, 3x3, 2,2, 1,1)
7	2012.2989501953	
cudnn.SpatialBatchNormalization
...
```
In my case the output at layer 6 is different by a lot. I understand that intermediate outputs can be different because of inplace operations, but the networks' output were different too. [I tried to build](https://gist.github.com/DmitryUlyanov/19890e9b0d379f2e452205e3ed115441) a standalone layer of type `cudnn.SpatialConvolution(32 -> 64, 3x3, 2,2, 1,1)` and see the difference, but there was none. Any Ideas?

**Comment by szagoruyko** [comment]
@DmitryUlyanov have run your script, can't reproduce. the errors are small.

**Comment by DmitryUlyanov** [comment]
Thanks, will try to reinstall drivers.

**Comment by DmitryUlyanov** [comment]
fixed by https://github.com/torch/nn/commit/e96093b5493e665b806dc61d58675d6d5c8ecc97
