### ISSUE TITLE
Does specifying a layer with dropout still require a nn.dropout layer afterwards?

### ISSUE THREAD

**Issue by dgcrouse** [soumith/cudnn.torch#252]
In [this fork](https://github.com/ngimel/torch-rnn) of torch-rnn (which I merged into [my own](https://github.com/dgcrouse/torch-rnn/tree/cudnn)), each of the CUDNN LSTM/RNN layers is followed by a nn.dropout layer with the same dropout value passed to the CUDNN layer. Is this redundant or necessary?

Layout resembles
`cudnn.LSTM with dropout 0.5 -> nn.dropout(0.5)`

**Comment by soumith** [comment]
seems redundant. now you're dropping out ~0.75 of units instead of 0.5

**Comment by dgcrouse** [comment]
That's what I thought, I just noticed that in the fork.

**Comment by ngimel** [comment]
In cudnn, dropout is applied between layers, but not after the last layer (I think it's in the manual) so you need to insert that last dropout, and that's what's done.

**Comment by dgcrouse** [comment]
Just saw that. Thanks for the feedback and for the fork, it's been really helpful in my own development.

**Comment by ngimel** [comment]
You are welcome.
