### ISSUE TITLE
Does 'groups' slows SpatialConvolution?

### ISSUE THREAD

**Issue by shenxiaolu1984** [soumith/cudnn.torch#253]
cudnn.SpatialConvolution(nInputPlane, nOutputPlane, kW, kH, [dW = 1], [dH = 1], [padW = 0], [padH = 0], [groups = 1])

e.g. nInputPlane = nOutputPlane. If I set groups = M, it has M connections instead of M*M connections, and should be much faster.

But when I test the following code, the time is 20.85598 vs 5.916371.
----
K = 3
M = 64
local x = torch.CudaTensor(6,M,64,64)

local t = os.clock()
for i=1,1000 do
    local y = cudnn.SpatialConvolution(M,M,K,K,1,1,1,1,M):cuda():forward(x)
end
print(os.clock()-t)

t = os.clock()
for i=1,1000 do
    local y = cudnn.SpatialConvolution(M,M,K,K,1,1,1,1):cuda():forward(x)
end
print(os.clock()-t)

**Comment by ngimel** [comment]
That's expected, as convolutions with nInputPlane=nOutputPlane=1 (essentially, what you are doing) are much less efficient, and submitting them to the different streams for concurrent execution that could have help a little bit was disabled due to the problems with workspace sharing.
