### ISSUE TITLE
libcudnn (R5) not found in library path 

### ISSUE THREAD

**Issue by rayset** [soumith/cudnn.torch#257]
new gtx 1070, installed cuda 8.0 and cudnn 5.1 ( echo $LD_LIBRARY_PATH gives /usr/local/cuda-8.0/lib64 and the files are in there) yet I get this error using cudnn as backend:

```
84: /home/rayset/torch/install/share/lua/5.1/cudnn/ffi.lua:1597: 'libcudnn (R5) not found in library path.
Please install CuDNN from https://developer.nvidia.com/cuDNN
Then make sure files named as libcudnn.so.5 or libcudnn.5.dylib are placed in your library load path (for example /usr/local/lib , or manually add a path to LD_LIBRARY_PATH)
```

I've tried all day, I'm on ubuntu 16 so I had to mess with gcc and g++.

Firstly I installed cudnn 5.1, then I added (but not removed the old ones) cudnn 5.0. could this be the problem?

here's what is in my cuda folders:

cuda-8.9/include: http://pastebin.com/1wuDgPmp

lib64: http://pastebin.com/bMKuXCk6

the files with the same name should all be from cudnn 5.0

here's my path:
/usr/local/cuda/lib64:/usr/local/cuda-8.0/lib64:/home/rayset/torch/install/lib:/home/rayset/torch/install/lib:

thanks in advance.

**Comment by soumith** [comment]
hi there, the error message that others suffered with is not the same as yours. I am actually unclear why your error happens.
Regardless, here's a solution:

```bash
export CUDNN_ROOT="/usr/local/cuda-8.0/lib64/libcudnn.so.5" # you can maybe add this line into ~/.bashrc for future use
luarocks install cudnn
```

To test that everything is successful:

```
th -lcudnn -e "print(cudnn.version)"
```

**Comment by rayset** [comment]
Thank you a lot! I can't believe it was something this simple.
I will report this fix over to neural style, I saw at least 3 other users with this problem. maybe the issue is in the tutorial over there :P 

I'm really impressed with cudnn memory usage,worth every euro.

**Comment by msiraj83** [comment]
@soumith .... yes i followed your instruction ...yes i execute the follow commond
`th -lcudnn -e "print(cudnn.version)"`
and got the results... as attached....
![cudnn_5 0](https://user-images.githubusercontent.com/8863047/32376994-f35e864a-c0d8-11e7-8b96-201178ed275d.png)

But again i got the same error when run the code in matlab...
