### ISSUE TITLE
CUDNN 5.1 Speedup?

### ISSUE THREAD

**Issue by dasguptar** [soumith/cudnn.torch#258]
The [CuDNN download page](https://developer.nvidia.com/cudnn) says that CuDNN 5.1 is supposed to give a `2.7x` speedup for VGG style convnets. However, simply by downloading, extracting and keeping CuDNN 5.1 files in the path, and re-running `luarocks install cudnn`, I am unable to observe any speedup.

`cudnn.version` gives me `5103`, but on a Titan X(Maxwell), I fail to see any speedup. Is it only for the newer generation(Pascal) of GPUs?

**Comment by szagoruyko** [comment]
@dasguptar do you set `cudnn.benchmark = true` ? be careful with 5.1 and benchmark mode, the new fast algorithms can hurt accuracy.

**Comment by dasguptar** [comment]
@szagoruyko without `cudnn.benchmark = true` and/or `cudnn.fastest=true`, I get speeds that are slower than CuDNN 5.0. Otherwise, I get pretty much the same speed as with CuDNN 5.0. I thought the newer CuDNN was supposed to give a speedup for VGG style convnets.. :open_mouth: 

P.S. A tangential question, but why do the fast algorithms hurt accuracy?

**Comment by szagoruyko** [comment]
@dasguptar `cudnn.benchmark = true` is enough, no need for `fastest`. See cudnn 5.1 manual for explanation why.

**Comment by dasguptar** [comment]
@szagoruyko , hmm, thanks for the pointers, but this still doesn't explain my original question.
Why might I not be seeing any speedup using CuDNN 5.1? Is it because I'm on a Maxwell card?

**Comment by ngimel** [comment]
I have old benchmarking data laying around. For vgg_a from convnet-benchmarks it was 475 ms on cudnn v5 and 348ms on cudnn v5.1 on Titan X. You have to use NONFUSED_WINO algorithm to get 348 ms, and that requires setting cudnn.benchmark=true. 2.7x claim compares cudnn v4 on K40 and cudnn v5.1 on M40 (same thing as Titan X, basically). If you are comparing the same hardware, performance gains are more modest.

**Comment by bearpaw** [comment]
@dasguptar Hi, I've been training my model with 
```
cudnn.fastest = true
cudnn.benchmark = true
```
And recently I could not repeat my results anymore (the results are much worse than before). Is it possible because of the upgrade of Torch and CUDNN 5.1? I'm currently using the newest version of torch and cudnn 5.1.

I'm not very familiar with cudnn.torch. Would you please give me some advice? Thank you!
