### ISSUE TITLE
Cannot Load Cudnn

### ISSUE THREAD

**Issue by chuankaian** [soumith/cudnn.torch#260]
Hi, there

I am trying to load cudnn with the command  module load cudnn/7.0 cuda/7.0    and system admin verifies that they are installed, but it still has the following cannot find 'cudnn' error.  Could someone tell me what's wrong about it? Thank you!
/share/apps/torch/20160408/bin/luajit: /share/apps/torch/20160408/share/lua/5.1/trepl/init.lua:384: module 'cudnn' not found:No LuaRocks module found for cudnn
        no field package.preload['cudnn']
        no file '/share/apps/torch/20160408/share/lua/5.1/cudnn.lua'
        no file '/share/apps/torch/20160408/share/lua/5.1/cudnn/init.lua'
        no file './cudnn.lua'
        no file '/share/apps/torch/20160408/share/luajit-2.0.4/cudnn.lua'
        no file '/usr/local/share/lua/5.1/cudnn.lua'
        no file '/usr/local/share/lua/5.1/cudnn/init.lua'
        no file '/home/anthill/chuankai/.luarocks/share/lua/5.1/cudnn.lua'
        no file '/home/anthill/chuankai/.luarocks/share/lua/5.1/cudnn/init.lua'
        no file '/share/apps/torch/20160408/lib/lua/5.1/cudnn.so'
        no file './cudnn.so'
        no file '/usr/local/lib/lua/5.1/cudnn.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file '/home/anthill/chuankai/.luarocks/lib/lua/5.1/cudnn.so'
stack traceback:
        [C]: in function 'error'
        /share/apps/torch/20160408/share/lua/5.1/trepl/init.lua:384: in function 'require'
        extract-features.lua:23: in main chunk
        [C]: in function 'dofile'
        ...pps/torch/20160408/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
        [C]: at 0x004051e0

**Comment by fmassa** [comment]
you don't have `mnist` package installed. This is not related to cudnn. Closing.

**Comment by chuankaian** [comment]
Sorry, I pasted the wrong logs. Now it's correct...

**Comment by fmassa** [comment]
did you install `cudnn-torch`? You need to have `cudnn` lib downloaded from NVidia website, and then run
```
luarocks install cudnn
```

**Comment by chuankaian** [comment]
The sys admin has done with   1. Install cuDNN (version R4 EA)
2. Have at least CUDA 7.0         
Let me forward the luarocks command to him. Thank you!

**Comment by fmassa** [comment]
just one information, you don't need sudo rights to install lua packages.

**Comment by chuankaian** [comment]
Oh, got it!  It works with luarocks install cudnn   Thank you very much!

**Comment by fmassa** [comment]
great. closing it then.
