### ISSUE TITLE
cuDNN sometimes does not work at all (but sometimes does)...

### ISSUE THREAD

**Issue by michael-p** [soumith/cudnn.torch#27]
Dear all,

I tried running a rather simple ConvNet using cuDNN (the supervised demo [1] where I replaced the convolutions, relu, and pooling by the cuDNN equivalents) and it sometimes trains fine, but sometimes just seems do be doing nothing at all (train and test error remain at the initial 19% global acc. forever). There are no errors reported. Using the cunn modules instead of the cuDNN ones also always works fine, so this seems to be a problem specific to cuDNN.

Another interesting thing: when I print the biases for some layers (same for the weights) using e.g.
```
print(model:get(1).bias:float())
```
they are all reported as nan's (in a run where cuDNN "hangs". Otherwise they are small numbers). Doing the same with the cunn-convolutions always prints nice small numbers.

Anyone else seen this problem before? Is there a way to at least detect when cuDNN "hangs" (besides monitoring the biases for nan's)? It's kind of annoying when your net is not learning at all and you do not know whether this is due to bad hyperparameters, or just because cuDNN hangs.

I'm on OSX 10.8 with Cuda 6.5 and cuDNN R2. I also use Caffe and Mocha with cuDNN backends and have never seen this problem occurring with these libs before.

Best
Michael

[1] https://github.com/torch/tutorials/blob/master/2_supervised/2_model.lua

**Comment by soumith** [comment]
there's a CuDNN R3 available which fixes some bugs, try that.

Second, can you post your model spec?

**Comment by soumith** [comment]
i meant R2RC3

**Comment by michael-p** [comment]
Ok after installing R2 RC3 and rebooting, it seems to work. Might be that it was indeed some strange bug in cuDNN. I'll close this issue for now and reopen should I experience this behavior again. Thank you very much for you help and for pointing me to cudnn R2RC3 !

PS: For completeness, this is the model spec:
```
nn.Sequential {
  [input -> (1) -> (2) -> (3) -> (4) -> (5) -> (6) -> (7) -> (8) -> (9) -> (10) -> (11) -> output]
  (1): cudnn.SpatialConvolution
  (2): cudnn.ReLU
  (3): cudnn.SpatialMaxPooling
  (4): cudnn.SpatialConvolution
  (5): cudnn.ReLU
  (6): cudnn.SpatialMaxPooling
  (7): nn.View
  (8): nn.Dropout
  (9): nn.Linear(1600 -> 128)
  (10): cudnn.ReLU
  (11): nn.Linear(128 -> 10)
}
```
Is there anything wrong with it?
