### ISSUE TITLE
Non-deterministic cudnn.SpatialConvolution backprop

### ISSUE THREAD

**Issue by jpuigcerver** [soumith/cudnn.torch#274]
Source showing the buggy behavior: https://gist.github.com/jpuigcerver/d9b43e9edcdc4ff12610e4174ca8d273

Either the cudnn.SpatialConvolution() wrapper or the NVIDIA implementation is buggy on the backprop pass. cudnn.SpatialConvolution() produces non-deterministic results.

I tested with Cuda 7.5.17 and Cuda 8.0.44, with cudnn 5.1.3 and 5.1.5 respectively, and the results are non-deterministic in both cases.

An example of the buggy behavior: two executions, using cudnn.SpatialConvolution (first) and nn.SpatialConvolution (second).

```
nn.SpatialConvolution	
forward 1  = a8e6b4f9d194c00a44a01577b66796ac     backward 1 = 070f3080f9213dcb27514cacf3cc91bc	
forward 2  = a8e6b4f9d194c00a44a01577b66796ac     backward 2 = 070f3080f9213dcb27514cacf3cc91bc	
forward 3  = a8e6b4f9d194c00a44a01577b66796ac     backward 3 = 070f3080f9213dcb27514cacf3cc91bc	
forward 4  = a8e6b4f9d194c00a44a01577b66796ac     backward 4 = 070f3080f9213dcb27514cacf3cc91bc	
forward 5  = a8e6b4f9d194c00a44a01577b66796ac     backward 5 = 070f3080f9213dcb27514cacf3cc91bc	
```

```
cudnn.SpatialConvolution	
forward 1  = a8e6b4f9d194c00a44a01577b66796ac     backward 1 = fc0a7e4a2e2a25cc8fe361fa4fa76f9b	
forward 2  = a8e6b4f9d194c00a44a01577b66796ac     backward 2 = 19c73fedd6d7154b3c2cd2621eaf8d29	
forward 3  = a8e6b4f9d194c00a44a01577b66796ac     backward 3 = 957ad96078ebc3bdd4b62f12f7509339	
forward 4  = a8e6b4f9d194c00a44a01577b66796ac     backward 4 = 2fea5e965ac89bf06a3ca953ebd0f380	
forward 5  = a8e6b4f9d194c00a44a01577b66796ac     backward 5 = c3f01d3a5d2be142fbd83b46503a9715
```

**Comment by soumith** [comment]
cudnn.SpatialConvolution produces non-deterministic results in backward. this is well documented and is mentioned in the manual.

**Comment by jpuigcerver** [comment]
Thank you very much, I was not aware of this behavior.
