### ISSUE TITLE
cudnn.SpatialConvolution with kernel of size 1

### ISSUE THREAD

**Issue by MichaelMathieu** [soumith/cudnn.torch#28]
Hi,

When I use cudnn.SpatialConvolution with kernels of size 1x1, it works correctly for the forward pass but  I don't get the expected result for the backprop : only the first plane is correct, the other ones are all zeros. Here is an piece of code failing :

require 'cudnn'
n = cudnn.SpatialConvolution(2, 2, 1, 1):cuda()
a = torch.randn(1, 2, 3, 3):cuda()
y = n:forward(a)
x = n:backward(a, y)
print(x)

If it is a bug of cudnn, it would be nice to at least have an assert to check for the kernel size.

Thanks!
Michael

**Comment by soumith** [comment]
If you update to cudnn r2-rc3, the bug is gone. It was in r2-rc1 and r2-rc2

**Comment by soumith** [comment]
And your example is giving 1 channel input to a 2 channel conv layer...

**Comment by MichaelMathieu** [comment]
I see, I will try to update.

My example seems fine to me, my input has minibatch of size 1 and 2 channels. Shouldn't there be an error otherwise ?

**Comment by soumith** [comment]
Ah yes you're right. The example is fine. Just upgrade and you should be good.
