### ISSUE TITLE
FindEx will not try to free memory when THC_CACHING_ALLOCATOR=1 and memory is full

### ISSUE THREAD

**Issue by szagoruyko** [soumith/cudnn.torch#283]
FindEx currently is based on the assumption that all memory is in use, and if THC_CACHING_ALLOCATOR=1 and no free memory available it will fail.
It probably should try to allocate or free something.
cc @borisfom

**Comment by borisfom** [comment]
Can you elaborate please?
Is it about FindEx not having its own oom handler (that would deallocate something and try again) - there won't be anything specific to caching allocator here. Or do you mean caching allocator fails to provide transparent interface to FindEx so it sees no memory when in fact it's all in the allocator cache ?
A repro example would be even bettter.

**Comment by ngimel** [comment]
FindEx relies on getMemoryUsage (which in turn gets mapped to cudaMemGetInfo) to determine maximum workspace size. 
https://github.com/soumith/cudnn.torch/blob/master/find.lua#L224
If all the memory is already allocated in caching allocator, workspace size will be 0, more or less, even though many blocks in caching allocator might be free. Trying to just allocate new storage can work, because there caching allocator will be able to pick up free blocks. Point is, with caching allocator one cannot rely on getMemoryUsage to say how much memory is available.

**Comment by szagoruyko** [comment]
@ngimel exactly, thanks Natalia.

**Comment by borisfom** [comment]
As I suggested above: this sis a bug in caching allocator (in my version I submitted earlier, cached allocator would overload getMemoryUsage so that the client does not have to know about the existence of the caching allocator. Should be fixed there.

**Comment by szagoruyko** [comment]
@borisfom thanks Boris! could you please point me to the code where this was done?
@soumith what do you think, should we add this to cutorch?

**Comment by soumith** [comment]
we should prob change cutorch.getMemoryUsage to reflect the memory usage - caching allocator's cached blocks, in case this allocator is used.

**Comment by borisfom** [comment]
@soumith: exactly, otherwise all Torch applications that rely on getMemoryUsage will be broken when caching allocator is in use.
@szagoruyko : sorry I seems top have lost my commits (my old closed PR now shows 0 commits). It should be straightforward though.

**Comment by borisfom** [comment]
@szagoruyko : update: I have recovered my cnmem pool commits and pushed them here for reference: https://github.com/NVIDIA/torch-cutorch/tree/cnmem_pool. Note that implementation at https://github.com/NVIDIA/torch-cutorch/blob/cnmem_pool/lib/THC/THCMemory.c#L78 only works well when the pool snatches all the memory in the beginning and do not expand later - then what we need is reporting from the pool. To cover the case of growing pool, you would simply need to sum those values. 
Now you may notice the third return value I was experimenting with: the largest block size - in fact, this is what most calls to getInfo are actually after (and not getting it). @soumith for some reason was against this extension so I did not even finish it - this may be worth discussing again.

**Comment by szagoruyko** [comment]
think we should cc @colesbury, Sam what do you think?
btw @borisfom if you have a temporary hack in mind I'd be happy to hear

**Comment by borisfom** [comment]
@szagoruyko , @soumith : why hack? We can get real solution in place.
I have started coding one. To get it right, I need to be able to enumerate all THC_states active for given device (I understand there coulld be more than one), can you suggest a good way to do that ?

**Comment by ngimel** [comment]
There is just a single device_allocator 
https://github.com/torch/cutorch/blob/master/lib/THC/THCCachingAllocator.cpp#L331
regardless of how many THCstates there are.

**Comment by borisfom** [comment]
Right, of course, thanks Natalia!
I will submit a PR later today.

**Comment by borisfom** [comment]
Submittedt https://github.com/torch/cutorch/pull/600

**Comment by borisfom** [comment]
@ngimel : this issue is resolved, can you please close it ?
