### ISSUE TITLE
Spurious negatives in SpatialConvolution gradInput

### ISSUE THREAD

**Issue by nhynes** [soumith/cudnn.torch#294]
For some reason, `updateGradInput` produces large negative values (e.g., -.0625) despite the input, gradOutput, weight, bias, and even output being non-negative. I have `cudnn.fastest, cudnn.benchmark = false, false` but the modes are non-deterministic*.

The module in question is a `SpatialConvolution(16 -> 16, 3x3, 1,1, 1,1)`. This doesn't happen with any of the 32->32s or 64->64s, so it's probably some issue with the specific algorithm CUDNN is using for that filter size.

Here's the relevant code from `SpatialConvolution.lua` starting on line 224.

```lua
assert(self.bias == nil)
assert(self.weight:min() >= 0)
assert(input:min() >= 0)
assert(self.output:min() >= 0)
assert(self.gradInput:min() >= 0)
assert(gradOutput:min() >= 0)
for g = 0,self.groups - 1 do
    checkedCall(self,'cudnnConvolutionBackwardData', cudnn.getHandle(), ...
end
assert(self.gradInput:min() >=0) -- fails
```

I'd greatly appreciate any tips!

\* because that yields `CUDNN_STATUS_INVALID_VALUE` for `cudnnConvolutionForward` despite that not even being documented in the CUDNN manual, but that's another issue entirely

**Comment by ngimel** [comment]
Do you have a minimal reproducing code? What cudnn version are you using? CUDNN_STATUS_INVALID_VALUE would typically be returned if your workspace is less than the workspace requested by a particular algo. What happens if you set cudnn.fastest to true?

**Comment by nhynes** [comment]
> Do you have a minimal reproducing code?

Unfortunately no, but I do have a [serialized copy of the offending module and its inputs](https://people.csail.mit.edu/nhynes/the_offending_module.t7), if you're interested.

> What cudnn version are you using? 

5.1 with CUDA 7 and 8 (the version of CUDA doesn't seem to make a difference).

> What happens if you set cudnn.fastest to true?

The same thing. I figured I'd try turning it off just in case 'fastest' causes CUDNN to get sloppy.

**Comment by nhynes** [comment]
> Do you have a minimal reproducing code?

~~Unfortunately no, but I do have a serialized copy of the offending module and its inputs, if you're interested.~~
Actually, the isolated, deserialized module works fine. Perhaps part of the issue is that the algorithm chosen is dependent on the memory used by the other convolutions' workspaces.

> What cudnn version are you using? 

5.1 with CUDA 7 and 8 (the version of CUDA doesn't seem to make a difference).

> What happens if you set cudnn.fastest to true?

The same thing. I figured I'd try turning it off just in case 'fastest' causes CUDNN to get sloppy.

**Comment by ngimel** [comment]
What if you add ```print("algo", bwdDataAlgo)``` after line 224 of SpatialConvolution.lua in the offending case, and attempt a reproducer manually setting this algo (using setMode function)?

**Comment by nhynes** [comment]
Ah ha! That does it. `ALGO_WINOGRAD` is the issue; setting it back to `ALGO_0` fixes the problem. For some reason, I'd never considered that it'd choose the former. Thanks a lot!

The numerical instability still perplexes me, though.

**Comment by soumith** [comment]
winograd in it's currently implemented form is unstable for backward.

**Comment by nhynes** [comment]
Thanks!

**Comment by ngimel** [comment]
@nhynes, can you please share your reproducer with winograd algorithm? 

Thanks!

**Comment by nhynes** [comment]
[Sure thing!](https://people.csail.mit.edu/nhynes/winobad.t7)
