### ISSUE TITLE
algorithm fallback from DATA_HALF to DATA_FLOAT broken

### ISSUE THREAD

**Issue by gchanan** [soumith/cudnn.torch#299]
I've experienced this on both Tesla P100 (cudnn-8.0) and Tesla M40 (cudnn-7.5) setups.  The issue appears to be in this function: https://github.com/soumith/cudnn.torch/blob/970d7249e5c680d20ecac98edebe1f507feeecac/find.lua#L71-L96

With these parameters, cudnnGetConvolutionNdDescriptor returns CUDNN_STATUS_NOT_SUPPORTED.

The cudnn documentation lists that CUDNN_STATUS_NOT_SUPPORTED is only returned if the the dimension requested is higher than CUDNN_DIM_MAX, so I played around with CUDNN_DIM_MAX in that function and 6 and below seems to work.  Both cudnn-8.0 and cudnn-7.5 define CUDNN_DIM_MAX as 8, so it looks like a cudnn bug.

**Comment by ngimel** [comment]
Do you have a small repro for a failing case? Thanks!

**Comment by gchanan** [comment]
No small repo right now, I discovered this while using https://github.com/facebook/fb.resnet.torch (yuck, actually you need my pull request https://github.com/facebook/fb.resnet.torch/pull/134 as well).

Then, running with cudnn-8.0 and "th main.lua -dataset cifar10 -depth 32 -precision half -nGPU 1" should reproduce the issue.  If you run with cudnn-7.5, you need to change "fasterHalfMathTypeForCurrentDevice()," to "CUDNN_DATA_HALF" on this line: https://github.com/soumith/cudnn.torch/blob/970d7249e5c680d20ecac98edebe1f507feeecac/init.lua#L112 and run the same command.

**Comment by borisfom** [comment]
Did you merge my PR https://github.com/soumith/cudnn.torch/pull/290 into your workspace ?

**Comment by borisfom** [comment]
Also, cuda 7.5 doesn't have Pascal support, so it should never try running native half. I will check if there is a loophole, but don't try.

**Comment by gchanan** [comment]
@borisfom when I get a chance I can try PR #290 on cudnn-8.0.

**Comment by borisfom** [comment]
@gchanan: please do! It has major bugfixes and whole new feature that actually tries both pseudo- and native FP16 and selects faster one.

**Comment by ngimel** [comment]
@gchanan, FWIW I can run cifar10 with @borisfom's  PR (P100, cuda 8.0). It is mostly (or may be even exclusively) picking pseudo-fp16 algorithms, though.

**Comment by soumith** [comment]
@ngimel you have the ability to merge PRs for cudnn.torch, so if there's any critical fixes pushed and I missed the notifications, do merge them :)
