### ISSUE TITLE
cudnn.SpatialConvolution breaks on 2x2 input with 3x3 kernel and pad=1

### ISSUE THREAD

**Issue by szagoruyko** [soumith/cudnn.torch#30]
nn.SpatialConvolution works fine in this case, cudnn v2rc3 breaks with C++ exception, maybe we should add an assert or search why does it break?

**Comment by soumith** [comment]
Can you file a bug report in NVIDIA: s bug tracker and paste the details here? I can add an assertion at the lua level for this case.

**Comment by szagoruyko** [comment]
I've checked v2 it gives CUDNN_BAD_PARAM instead of a seg fault, so I don't know, probably it would be better to assert in this case also in order not to wonder around the net trying to figure out why does it give BAD_PARAM

**Comment by szagoruyko** [comment]
fixed in R3
