### ISSUE TITLE
Trouble with SpatialConvolution

### ISSUE THREAD

**Issue by alashkari** [soumith/cudnn.torch#301]
Hello everyone,

I am trying to run a pre-trained [model](https://github.com/harvardnlp/seq2seq-attn) on my machine. The problem is that when I intend to load the model, I get this error:

~/torch/install/bin/luajit: ~/.luarocks/share/lua/5.1/torch/File.lua:343: unknown Torch class <cudnn.SpatialConvolution>
stack traceback:
	[C]: in function 'error'
	/home/rui/.luarocks/share/lua/5.1/torch/File.lua:343: in function 'readObject'
	/home/rui/.luarocks/share/lua/5.1/torch/File.lua:369: in function 'readObject'
	/home/rui/.luarocks/share/lua/5.1/torch/File.lua:369: in function 'readObject'
	/home/rui/.luarocks/share/lua/5.1/torch/File.lua:369: in function 'readObject'
	/home/rui/.luarocks/share/lua/5.1/torch/File.lua:369: in function 'readObject'
	/home/rui/.luarocks/share/lua/5.1/torch/File.lua:353: in function 'readObject'
	/home/rui/.luarocks/share/lua/5.1/torch/File.lua:369: in function 'readObject'
	/home/rui/.luarocks/share/lua/5.1/torch/File.lua:369: in function 'readObject'
	/home/rui/.luarocks/share/lua/5.1/torch/File.lua:353: in function 'readObject'
	/home/rui/.luarocks/share/lua/5.1/torch/File.lua:369: in function 'readObject'
	...
	/home/rui/.luarocks/share/lua/5.1/torch/File.lua:351: in function 'readObject'
	/home/rui/.luarocks/share/lua/5.1/torch/File.lua:369: in function 'readObject'
	/home/rui/.luarocks/share/lua/5.1/torch/File.lua:369: in function 'readObject'
	/home/rui/.luarocks/share/lua/5.1/torch/File.lua:409: in function 'load'
	./beam.lua:505: in function 'init'
	evaluate.lua:5: in function 'main'

I should tell you that I have installed Cuda (V8) and cuDNN, and I don't have any problem when I start to train the model myself. This error occurs when I try to use a pre-trained model.

Thank you for your time and help in advance.

**Comment by ngimel** [comment]
Try adding 
```
require 'cudnn'
```
before loading model.

**Comment by alashkari** [comment]
Thank you ngimel. I noticed where I was wrong. It was not with the cudnn module.
