### ISSUE TITLE
Wrong number of parameters with cudnn.BLSTM

### ISSUE THREAD

**Issue by starsplash** [soumith/cudnn.torch#311]
Hi,

given following code 
```
require "cudnn"
torch.setdefaulttensortype('torch.FloatTensor')
local test = cudnn.BLSTM(512,512,1,false,0)
print(test.weight:size(1))
```
the output is `4202497` but should be `4202496` (i.e. number of parameters).

However, I got `4202496` when I comment out `torch.setdefaulttensortype('torch.FloatTensor')`.

Any idea what is going on?
Thanks!

Some details:
- cudnn version: 5.1
- CUDA version: 8.0
- Torch version: 7

**Comment by ngimel** [comment]
That's a bug somewhere in torch. The following snippet
```
wsize = (512*512*16+512*16)*4
tmp = (wsize + 3) / 4
print(tmp, torch.floor(tmp))
torch.setdefaulttensortype('torch.FloatTensor')
print(tmp, torch.floor(tmp))
```
outputs 
```
4202496.75	4202496	
4202496.75	4202497	
```

**Comment by starsplash** [comment]
ok, thank you for the quick reply!
