### ISSUE TITLE
cudnn Sigmoid significantly lower than regular Sigmoid

### ISSUE THREAD

**Issue by jsenellart-systran** [soumith/cudnn.torch#314]
I am comparing 50000 forward on Sigmoid for a tensor 64x5000 and I get significantly slower (~3 times slower) using cudnn.Sigmoid than using regular nn.Sigmoid. Am I doing something wrong? Is it known?

```
net=nn.Sigmoid():cuda()
t=torch.CudaTensor(64,5000)
timer=torch.Timer()
for _=1, 50000 do
  net:forward(t)
end
print('GPU',timer:time().real)

net = cudnn.convert(net, cudnn)
timer=torch.Timer()
for _=1, 50000 do
  net:forward(t)
end
print('CUDNN',timer:time().real)
```

**Comment by soumith** [comment]
this is prob the culprit: https://github.com/soumith/cudnn.torch/blob/master/Pointwise.lua#L36
A long long time ago, i did this around CuDNN R1 to get stuff to work.
Changing that to the actual shape of the tensor, does it improve things?

**Comment by jsenellart-systran** [comment]
Thanks for this super fast hint!

I looked at how Pointwise was working: indeed the initialization of descriptors is taking a bit of time but only once since there is cache (based on the size), so I added a first `net:forward(t)` before the loop to preinit - also, I tried with larger tensors:

|  Tsize | GPU | CUDNN | CUDNN with preinit |
|-|------|---------|--------------------|
| 64x5000 | 0.8 | 2.4 | 2.1 |
| 64x5000x10 | 7.0 | 4.2 | 3.9 |
| 64x5000x100 | 68 | 38 | 38 |

so `cudnn.Sigmoid` is twice faster than `cunn.Sigmoid` - but it shows only on large enough tensor - so bad for NMT with only 4x1000 cells by layer! 

Thanks @soumith - since I am benchmarking I will add some other benchmark for other modules before closing.

**Comment by jsenellart-systran** [comment]
_run on TitanX Pascal - 50000 iterations_

| Module | Tsize | GPU | CUDNN (w/ preinit) |
|-|-|-|-|
| Sigmoid | 64x5000 | 0.8 | 2.1 |
| Sigmoid | 64x50000 | 7.0 | 3.9 |
| Sigmoid | 64x500000 | 68 | 38 |
| SoftMax | 64x5000 | 1.6 | 3.1 |
| SoftMax | 64x50000 | 24.3 | 13.1 |
| SoftMax | 64x100000 | 46.2 | 23.6 |
