### ISSUE TITLE
documentation for CUDNN_BIDIRECTIONAL

### ISSUE THREAD

**Issue by jsenellart-systran** [soumith/cudnn.torch#316]
Hello,

in cudnn (5.1) API reference - API for `CUDNN_BIDIRECTIONAL` is different than what you have implemented in RNN.lua: indeed in cudnn doc (page 124) for cudnnRNNForwardTraining, `hxDesc`, `cxDesc` and the others are supposed to be `numLayer x batch x 2 hiddenSize` - and what you implemented in RNN.lua is `2 numLayer x batch x hiddenSize`.

Your implementation works (and I tried to implement what is specified in cudnn API and it does not work) - but I can not find documentation for the `2 numLayers` - is the first half `{1,numLayer}` for one direction and the second half `{numLayer,2 numLayer}` for the other one or the 2 directions are odd/even indices?

Thanks

**Comment by ngimel** [comment]
Hello, 

Thanks for pointing out error in the documentation, we will fix it for the future releases. As for your second question, 2 directions are odd/even indices, we will make sure to add this to the documentation.

**Comment by jsenellart-systran** [comment]
Thanks @ngimel!
