### ISSUE TITLE
FP16 usage

### ISSUE THREAD

**Issue by shuzi** [soumith/cudnn.torch#317]
Hi,  how should I use FP16 mode for cudnn package?
I got the following error
![image](https://cloud.githubusercontent.com/assets/6613848/22279510/434538c6-e299-11e6-8bdc-0927a4e2aaf9.png)

**Comment by ngimel** [comment]
You also have to convert the layer itself to CudaHalfTensor.

**Comment by shuzi** [comment]
@ngimel 

would you please show an example to convert the layer ?
I tried following ways which do not work

![image](https://cloud.githubusercontent.com/assets/6613848/22316586/29f4a340-e33c-11e6-837a-bde32b7880fb.png)

**Comment by ngimel** [comment]
model = cudnn.TemporalConvolution(10,12,2,1,0):type('torch.CudaHalfTensor')

**Comment by shuzi** [comment]
@ngimel 

Thanks a lot!  :+1:
