### ISSUE TITLE
Cannot launch more than one instance on K80

### ISSUE THREAD

**Issue by Junonia** [soumith/cudnn.torch#32]
After the update,  only one instance of cudnn can be run on K80.  When I try to launch another one, it gave the following error.

/usr/local/torch/install/share/lua/5.1/cudnn/init.lua:26: Error in CuDNN: CUDNN_STATUS_INTERNAL_ERROR

I reverted back to the old version and it works again.

**Comment by soumith** [comment]
hi, this might be fixed now with the latest cudnn.torch. give it a try.
