### ISSUE TITLE
buffer size is in bytes, fix it in bindings

### ISSUE THREAD

**Issue by soumith** [soumith/cudnn.torch#33]
Someone from nvidia pointed out that the buffersize returned by cudnnGetConvolutionForwardWorkspaceSize is the number of bytes.

So I am allocating excessive memory here because I thought the size was the number of floats needed. fix it.

**Comment by deltheil** [comment]
*You probably noticed that too, but just in case:*

In the same spirit [`cudnnConvolutionForward`](https://github.com/soumith/cudnn.torch/blob/d45b3db/SpatialConvolution.lua#L174) expects the workspace size in bytes (so far `nElement()` is used, so it will have to be changed when `cudnnGetConvolutionForwardWorkspaceSize` gets fixed).
