### ISSUE TITLE
cudnn error

### ISSUE THREAD

**Issue by varghesealex90** [soumith/cudnn.torch#335]
Hi;
I accidentally removed perfectly working Torch. Now I am facing problem with cudnn. 

Here is the pipeline of what I did: 
Install cuda toolkit  8.0 
 
1) Install torch from scratch as per http://torch.ch/docs/getting-started.html
2) unzip cudnn 8.0 and copy files (libcudnn.so.5.1.10 & all other files in the folder) in lib64 to /usr/local/cuda-8.0/lib64  
3). cloned to cudnn.torch and ran luarocks make cudnn-scm-1.rockspec
4) set bashrc as following
export CUDA_HOME=/usr/local/cuda-8.0
export LD_LIBRARY_PATH=${CUDA_HOME}/lib64:$LD_LIBRARY_PATH
export PATH=${CUDA_HOME}/bin:${PATH}

5) source ~/.bashrc
6) th
require 'cutorch' -- works
require 'cunn' --- true
require 'cudnn' -- error

THCudaCheck FAIL file=/home/bmi/torch/extra/cutorch/init.c line=261 error=46 : all CUDA-capable devices are busy or unavailable
/home/bmi/torch/install/share/lua/5.1/trepl/init.lua:389: /home/bmi/torch/install/share/lua/5.1/trepl/init.lua:389: /home/bmi/torch/install/share/lua/5.1/cudnn/find.lua:165: cuda runtime error (46) : all CUDA-capable devices are busy or unavailable at /home/bmi/torch/extra/cutorch/init.c:261
stack traceback:
	[C]: in function 'error'
	/home/bmi/torch/install/share/lua/5.1/trepl/init.lua:389: in function 'require'
	[string "_RESULT={require 'cudnn'}"]:1: in main chunk
	[C]: in function 'xpcall'
	/home/bmi/torch/install/share/lua/5.1/trepl/init.lua:661: in function 'repl'
	.../bmi/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:204: in main chunk
	[C]: at 0x00406670	

Could someobne help me with this

**Comment by soumith** [comment]
did you try restarting your machine?
Also, what's the output of the command `nvidia-smi`

**Comment by varghesealex90** [comment]
Hi;

I just tried resarting the computer. No change in the output. Before restarting I tried the following too
luarocks install torch
luarocks install nn
luarocks install cutorch
luarocks install cunn
luarocks install cudnn 

![soumith](https://cloud.githubusercontent.com/assets/10129358/23168463/3f68bff8-f86e-11e6-97c3-92423400b794.png)

**Comment by soumith** [comment]
could you try:

`CUDA_VISIBLE_DEVICES=0 th`

alternatively:

`CUDA_VISIBLE_DEVICES=1 th`

**Comment by varghesealex90** [comment]
where should I hit this piece of code?

**Comment by varghesealex90** [comment]
oh yes it works.. Thanks Soumith

**Comment by varghesealex90** [comment]
Could you please tell why such a problem arises? Feel free to close the issue

**Comment by varghesealex90** [comment]
Is there way to fix this , so that I could easily use "cudnn" just by using the "th" function?

**Comment by soumith** [comment]
i presume your GPU `NVS 335` is not supported by CuDNN 5.1 maybe
