### ISSUE TITLE
Broken tar invocation in FindCUDNN.cmake

### ISSUE THREAD

**Issue by akinmr** [soumith/cudnn.torch#350]
Hi,

I faced following error during Torch installation:
> CMake Error: Problem with archive_read_open_file(): Failed to open '--format=tgz'
> CMake Error: Problem extracting tar: --format=tgz
"tar xzvf" command does not take --format option just after "f" option and refuses to unpack archive.
In addition to that, tar usually auto-detects compression format when the archive is normal file.
So, --format option is completely useless and harmful in this case.
When I remove the option, like attached patch, it works well.

[findcudnn-tar-option.diff.txt](https://github.com/soumith/cudnn.torch/files/823403/findcudnn-tar-option.diff.txt)

**Comment by soumith** [comment]
thanks, fixed via https://github.com/soumith/cudnn.torch/commit/744f79b10b20a2c7561ae352f923f2b331583fcd
