### ISSUE TITLE
spacialConvolution backward computation returns null

### ISSUE THREAD

**Issue by bjuncek** [soumith/cudnn.torch#353]
Does anyone have an idea on why the module containing spacialConvolution without bias would return null when the following command is ran 
```module:backwards(input:cuda(), gradOutput)```

Interesting thing is, when `backward` is computed on in an intermediate layer, it returns expected value (gradOutput), but when calculated on the first layer/module, it returns `null`.

**Comment by ngimel** [comment]
Typically, you don't need gradient with respect to data for your first layer (you only need it to propagate error through the network, when you are already in the first layer, there's nowhere to propagate error to).

**Comment by bjuncek** [comment]
Well, if you want to implement [guided backpropagation](https://arxiv.org/pdf/1412.6806.pdf), you need to get a reconstructed image by propagating the gradient all the way through. Is there a workaround around that (adding an identity or view layer at the beginning)?

**Comment by ngimel** [comment]
How do you define your model? Unless you set gradInput=nil for the first layer, the gradient should be calculated.

**Comment by bjuncek** [comment]
Ok, I was an idiot - I wanted to avoid computing bias gradient, but I left the gradinput as nil as well. Thanks for the debugging help!
