### ISSUE TITLE
Questions about cudnn.BLSTM output concatenation order

### ISSUE THREAD

**Issue by gmsh** [soumith/cudnn.torch#357]
Hi,
The questions is about the order of cudnn.BLSTM's output  sequence.
For example, the input sequence is 
```
x_1, x_2, x_3, x_4, x_5
```
and `F(x_t)` means the output of the forward LSTM, `B(x_t) `for the backward one. `[a,b]` means the concatenation of `a` and `b`.
The manual says 
>Each layer of the the network iterates recurrently from the first input to the last and separately from the last input to the first. The outputs of the two are concatenated at each iteration giving the output of the layer. 

So which one below is the output sequences? I could not find other references or examples. Please help me with this. Thanks for advance.
```
[F(x_1), B(x_1)]
[F(x_2), B(x_2)]
[F(x_3), B(x_3)]
[F(x_4), B(x_4)]
[F(x_5), B(x_5)]
```
or 
```
[F(x_1), B(x_5)]
[F(x_2), B(x_4)]
[F(x_3), B(x_3)]
[F(x_4), B(x_2)]
[F(x_5), B(x_1)]
```
or 
```
[B(x_1), F(x_1)]
[B(x_2), F(x_2)]
[B(x_3), F(x_3)]
[B(x_4), F(x_4)]
[B(x_5), F(x_5)]
```
or
```
[B(x_1), F(x_5)]
[B(x_2), F(x_4)]
[B(x_3), F(x_3)]
[B(x_4), F(x_2)]
[B(x_5), F(x_1)]
```
@soumith @ngimel

**Comment by ngimel** [comment]
It's the first one. See also #316.

**Comment by gmsh** [comment]
thanks @ngimel
