### ISSUE TITLE
Issue while installing CuDNN

### ISSUE THREAD

**Issue by zadraninn** [soumith/cudnn.torch#359]
I'm using Ubuntu 16.04 and I'm trying to install CuDNN from download site: https://developer.nvidia.com/rdp/cudnn-download
and followed Install Guide but I'm getting error:

These bindings are for CUDNN 5.x (5005 <= cudnn.version > 6000) , while the loaded CuDNN is version: 6020  
Are you using an older or newer version of CuDNN?

I even copied downloaded libraries into my usr/local/cuda folder, still without success. I have CUDA Version 8.0.61. What can I do next?

Thank you.

**Comment by ngimel** [comment]
You have to use r6 branch of these bindings to use cudnn v6.

**Comment by zadraninn** [comment]
I replaced my lua binding files with those from R6 branch and it worked. Thanks ngimel, closing issue now.

**Comment by Laurawly** [comment]
I switched cudnn.torch to branch R6 and did an new luarocks install cudnn-scm-1.rockspec, but when I ran th -e "require 'cudnn'" it still gave me this error: ...s/leywang/torch/install/share/lua/5.1/trepl/init.lua:389: ...s/leywang/torch/install/share/lua/5.1/trepl/init.lua:389: ...rs/leywang/torch/install/share/lua/5.1/cudnn/ffi.lua:1618: These bindings are for CUDNN 5.x (5005 <= cudnn.version > 6000) , while the loaded CuDNN is version: 6021
Are you using an older or newer version of CuDNN?

Did I miss something?

**Comment by ashleyjamesbrown** [comment]
Im having the same problem. Can you tell me how to install or swap to the new branch please ?

**Comment by ngimel** [comment]
```git clone https://github.com/soumith/cudnn.torch.git -b R6 && cd cudnn.torch && luarocks make cudnn-scm-1.rockspec```

**Comment by prismformore** [comment]
@ngimel Just fix the problem perfectly, cheers!

**Comment by hrdkjain** [comment]
R<cuDNN Version number> solves the problem for CuDNN7.0 as well

**Comment by GuilinZ** [comment]
@ngimel ,hi, when i use 
git clone https://github.com/soumith/cudnn.torch.git -b R6 && cd cudnn.torch && luarocks 
I got an error saying that it calls a nil value 
lua5.1: /usr/local/share/lua/5.1/luarocks/help.lua:14: attempt to call field 'this_program' (a nil value)
stack traceback:
	/usr/local/share/lua/5.1/luarocks/help.lua:14: in main chunk
	[C]: in function 'require'
	/usr/bin/luarocks:10: in main chunk
	[C]: ?
Could you pls help me fix this?
