### ISSUE TITLE
Can not require 'cudnn' when some of the GPUs are fully used

### ISSUE THREAD

**Issue by lr87** [soumith/cudnn.torch#362]
I'm using a machine with 6 GPUs. I found that, when I use " require 'cudnn' " in torch, it will occupy some memory in each GPU, several hundreds M. So, if some of the GPUs are fully used, there's not enough memory in them to initialize the cudnn. Following are the messages:

th> require 'cudnn'
Found Environment variable CUDNN_PATH = /home/liran/cudnn/lib64/libcudnn.so.5	
THCudaCheck FAIL file=/home/liran/torch/extra/cutorch/init.c line=764 error=2 : out of memory
/home/liran/torch/install/share/lua/5.1/trepl/init.lua:389: /home/liran/torch/install/share/lua/5.1/trepl/init.lua:389: /home/liran/torch/install/share/lua/5.1/cudnn/ffi.lua:1624: cuda runtime error (2) : out of memory at /home/liran/torch/extra/cutorch/init.c:764
stack traceback:
	[C]: in function 'error'
	/home/liran/torch/install/share/lua/5.1/trepl/init.lua:389: in function 'require'
	[string "_RESULT={require 'cudnn'}"]:1: in main chunk
	[C]: in function 'xpcall'
	/home/liran/torch/install/share/lua/5.1/trepl/init.lua:661: in function 'repl'
	...iran/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:199: in main chunk
	[C]: at 0x00406670	

Actually I just want one GPU to work with. I'm wondering how can I select one or some GPUs to initialize the cudnn, rather than use all the GPUs ?

**Comment by ngimel** [comment]
you should set CUDA_VISIBLE_DEVICES env var to just the GPU you want to run on.

**Comment by lr87** [comment]
@ngimel That works ! Thank you very much!
