### ISSUE TITLE
Machine GPU type dependency: invalid device function

### ISSUE THREAD

**Issue by farleylai** [soumith/cudnn.torch#381]
While the nVidia libcudnn for Linux is the same binary regardless of GPU models, the torch cudnn binding seems not and must be rebuilt. This makes it not so straightforward to simultaneously train different models on machines equipped with different GPU types.

If the GPU on a target machine with a different type (1080Ti) from the building machine (TITAN X), the following error is thrown:
THCudaCheck FAIL file=/path/to/torch/extra/cutorch/lib/THC/THCTensorCopy.cu line=204 error=8 : invalid device function
/path/to/torch/install/bin/luajit: ...src/SparkplugTrainer.lua:134: cuda runtime error (8) : invalid device function at /path/to/torch/extra/cutorch/lib/THC/THCTensorCopy.cu:204

The use case is to build torch once for multiple machines to use despite different GPU types.
Is that really necessary to rebuild torch for each?

**Comment by ngimel** [comment]
This issue has nothing to do with cudnn.torch and belongs in torch/cutorch. Yes, cutorch has to be built for all the architectures you want to use it on. You can set env variable TORCH_CUDA_ARCH_LIST to build cutorch for all the architectures you care about.
