### ISSUE TITLE
LRNs have different names in inn and R3

### ISSUE THREAD

**Issue by szagoruyko** [soumith/cudnn.torch#40]
inn | cudnn R3
--- | ---
inn.SpatialCrossResponseNormalization | cudnn.SpatialCrossLRN
inn.SpatialSameResponseNormalization | cudnn.SpatialDivisiveNormalization

also cudnn.SpatialCrossLRN has different default parameters. Should we maybe use inn naming and defaults?

cc @fmassa

**Comment by soumith** [comment]
That sounds good to me. Sorry, did not notice in inn

**Comment by szagoruyko** [comment]
Will do a PR
