### ISSUE TITLE
Backward compatibility is broken in R3 average pooling

### ISSUE THREAD

**Issue by szagoruyko** [soumith/cudnn.torch#42]
https://github.com/soumith/cudnn.torch/blob/R3/SpatialAveragePooling.lua#L6 mode is different when loaded from older versions

**Comment by soumith** [comment]
ok, so the older versions excluded the padding for average? There's a mode for that as well:
https://github.com/soumith/cudnn.torch/blob/R3/ffi.lua#L362

**Comment by szagoruyko** [comment]
no, loaded module has ```self.mode = 'CUDNN_POOLING_AVERAGE'``` and it's not defined in ffi

**Comment by soumith** [comment]
oh i see, backcompatibility of existing modules... yea got it
