### ISSUE TITLE
R3: Modes may not be applied

### ISSUE THREAD

**Issue by mys007** [soumith/cudnn.torch#44]
First of all, thanks for the very fast porting to R3. I noticed that `fastest()`, `setMode()` or `resetMode()` are ineffective once a forward pass has been done because `createIODescriptors()` is not fully executed. Suggested fix: add `self.iSize:fill(0)` to each function.

**Comment by soumith** [comment]
fixed via https://github.com/soumith/cudnn.torch/commit/97f41c48602a345344bb5f76e73e4b2fbf7eb679
