### ISSUE TITLE
"Warning: cannot write object field <weightDesc>"

### ISSUE THREAD

**Issue by szagoruyko** [soumith/cudnn.torch#6]
I've got tons of annoying warnings when saving cudnn networks:

```
$ Warning: cannot write object field <weightDesc>
$ Warning: cannot write object field <biasDesc>
$ Warning: cannot write object field <iDesc>
$ Warning: cannot write object field <convDesc>
$ Warning: cannot write object field <oDesc>
$ Warning: cannot write object field <iDesc>
$ Warning: cannot write object field <oDesc>
$ Warning: cannot write object field <weightDesc>
$ Warning: cannot write object field <biasDesc>
$ Warning: cannot write object field <iDesc>
$ Warning: cannot write object field <convDesc>
$ Warning: cannot write object field <oDesc>
```

Is it possible to suppress them?

**Comment by ibmua** [comment]
Could you, please, elaborate a bit on how to perform that niling?

**Comment by szagoruyko** [comment]
I use this function
https://gist.github.com/szagoruyko/b6e70f6c6be9a8399c10

**Comment by ibmua** [comment]
Thanks a lot, works like charms! Soumith should add this to the package by default, IMO, everybody needs it anyway. And it's better if we won't have to include it separately. Just make it something like mlp:prepare_to_save()

**Comment by soumith** [comment]
fixed this in trunk https://github.com/soumith/cudnn.torch/commit/d45b3db9fdce44a75230a8dffe3a17871d5e7611
