### ISSUE TITLE
SpatialConvolution weights are kW x kH, should be kH x kW

### ISSUE THREAD

**Issue by tomsercu** [soumith/cudnn.torch#68]
When kH ~= kW, the weight & gradWeight has the size ```nOutputPlane x nInputPlane x kW x kH```.
However, the cudnn kernels interpret the memory as having the size ```nOutputPlane x nInputPlane x kH x kW```, which is consistent with nn.SpatialConvolution and nn.SpatialConvolutionMM. See example below which uses a convolution to mask an input tensor.
I could just submit a PR with a correct __init() function, or should we care about the fact that loaded old cudnn models will still have the wrong tensor view? I suspect we shouldn't worry, since even loading a weight tensor with the wrong view will still be interpreted correctly.

```
require 'cudnn'
kH, kW = 3,2
inp = torch.range(1, 6):view(1, 1, kH, kW)
net = cudnn.SpatialConvolution(1,1,kW,kH):cuda()
net.bias:zero()
net.weight:zero()
net.weight[{1,1,2,1}]=1
print("input")
print(inp)
print("cudnn: should be 1x1x3x2 instead of 1x1x2x3")
print(net.weight)
print("as demonstrated by the corresponding position in the input tensor")
print(net:forward(inp:cuda()):squeeze())
net2 = nn.SpatialConvolution(1,1,kW,kH)
net2.weight:copy(net.weight) -- copy despite different sizes
net2.bias:zero()
print("nn version has the right layout":)
print(net2.weight)
print(net2:forward(inp):squeeze())
```

**Comment by szagoruyko** [comment]
yes, send a PR please, saved models will not be affected because weight:size() is not used anywhere inside.
