### ISSUE TITLE
fp16/half precision support

### ISSUE THREAD

**Issue by lukasc-ch** [soumith/cudnn.torch#79]
What is the current status on the half precision stuff? With the Tegra X1 out, this is becoming more interesting. I have seen that @soumith has committed some first stuff with 27e969b094ee6d50fcbbac50d4b73d53881613b3. Is anyone working on this? I would generally be interested on contributing to this. Are there some thoughts around on how this should best be done with CudaTensor currently supporting single-precision exclusively?

**Comment by soumith** [comment]
As soon as https://github.com/torch/cutorch/pull/225 is merged, we can enable half precision. Should be merged this week.

**Comment by Darktex** [comment]
Hi soumith, any progress on this?

**Comment by jcjohnson** [comment]
Any idea when we will see FP16 support? https://github.com/torch/cutorch/pull/225 Seems to have been merged a while back.

**Comment by jorditg** [comment]
+1

**Comment by lukasc-ch** [comment]
FYI, stuff is moving: PR #170, and szagoruyko/cudnn.torch/fp16

**Comment by victorhcm** [comment]
That'd be great, specially if the GTX 1080 will really support double rate at half precision.

**Comment by campbx** [comment]
Is FP16 still under development?  What is the ETA?  Thanks!

**Comment by szagoruyko** [comment]
@campbx there are 2 pull requests ongoing: https://github.com/soumith/cudnn.torch/pull/206 and https://github.com/torch/cutorch/pull/431, fp16 is working and tested and hopefully will be merged soon after little modifications.

**Comment by jorditg** [comment]
Hi all, I've seen that #206 and torch/cutorch#431 are ready. 

When fp16 is expected to be merged?

**Comment by soumith** [comment]
They've been merged now. Thanks everyone, and especially @szagoruyko
