### ISSUE TITLE
Groups problem with benchmark/fastest

### ISSUE THREAD

**Issue by mys007** [soumith/cudnn.torch#99]
There seems to be a problem with groups in SpatialConvolution and cudnn.benchmark or cudnn.fastest options. They seem to produce different results w.r.t. the standard mode.  Let's have the following code 
```
require 'torch'
require 'cudnn'

local g = 1 --2
local M = cudnn.SpatialConvolution(384,384, 3,3, 1,1, 1,1, g):cuda()
local M2 = M:clone()

for i=1,10 do
    local p = torch.CudaTensor(1,384,16,16):normal(0,1)
    cudnn.benchmark = false
    M:forward(p)
    cudnn.benchmark = true
    M2:forward(p)

    local a = M.output
    local b = M2.output
    print(i,(a-b):norm(),(a-b):abs():max())
end
```
On my Titan Black and cudnn v3, g=1 outputs zeros but g=2 outputs nonzeros. On Sergey's Titan Black and v4, g=2 outputs zeros sometimes and on Titan X it "hangs". Any explanations?

**Comment by szagoruyko** [comment]
not fixed in 4.0.7.

**Comment by soumith** [comment]
I'm on titan-x and 4.0.7 btw, and it does not hang.

This is my output:

1       0.0001847633975558      5.1259994506836e-06
2       0.00018488783098292     5.7220458984375e-06
3       0.00018576718866825     6.1988830566406e-06
4       0.00018560829630587     6.0796737670898e-06
5       0.00018510696827434     5.7220458984375e-06
6       0.00018462113803253     6.3180923461914e-06
7       0.00018808274762705     5.8412551879883e-06
8       0.00018529174849391     5.1259994506836e-06
9       0.00018367868324276     6.4373016357422e-06
10      0.00018582359189168     4.887580871582e-06

**Comment by szagoruyko** [comment]
did you set g = 2 ?

**Comment by soumith** [comment]
oh, right, i just did that and it hangs. wtf!

**Comment by ngimel** [comment]
The same self.extraBuffer is used for the different kernels running in the different streams (lines 372-387 of SpatialConvolution.lua). One should not do that, that's an error in torch bindings.

**Comment by soumith** [comment]
ok i'm going to remove the streams optimization altogether, with cudnn we dont actually see speedups with streams. Thanks for investigating Natalia.

**Comment by szagoruyko** [comment]
thanks Natalia!

**Comment by jdemouth** [comment]
To add to what Natalia said, we use a spin lock at the end of that kernel to make sure we get deterministic results and that lock uses a buffer of counters in global memory (one counter per block of CUDA threads in the XY plane of a grid). If two streams share a workspace, one "stream" may reset the counters while the other "stream" is using them. That's a bad idea ;).
